[package]
authors = ["Crypto Garage"]
edition = "2018"
name = "mocks"
version = "0.1.0"

[dependencies]
bitcoin = "0.31.2"
dlc = {path = "../dlc"}
dlc-manager = {path = "../dlc-manager"}
dlc-messages = {path = "../dlc-messages"}
lightning = {version = "0.0.123"}
secp256k1-zkp = {version = "0.10.1", features = ["global-context", "rand", "rand-std"]}
simple-wallet = {path = "../simple-wallet"}
